// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpDevLib.Extensions.Tests.Data;

#nullable disable

namespace SharpDevLib.Extensions.Tests.Data.Migrations.BarDB
{
    [DbContext(typeof(BarDbContext))]
    [Migration("20220804092003_BarFoo")]
    partial class BarFoo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("SharpDevLib.Extensions.Tests.Data.BarSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BarSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
